global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: realworld_rust_axum_sqlx_kit_docker
    static_configs:
      - targets:
          - realworld_rust_axum_sqlx_conduit:8080
  - job_name: realworld_rust_axum_sqlx
    static_configs:
      - targets:
          - localhost:8080
